log:
    log_file_path: log/memory.log

# readFile: D:\tools\fm20240923\fm20240923.zip
reader:
    read_file_paths: [D:\temp\ubuntu.iso, D:\Software\VM_VirtualMachine]
    big_block_size: 1024*1024  # 1MB
    block_size: 1024*4     # 4KB
    range:
        lower: 0.0   # 30%
        hight: 1.0

# 求解器使用的配置
solver_options: 
    p : 0.3