log:
    log_file_path: log/memory.log

# readFile: D:\tools\fm20240923\fm20240923.zip
reader:
    read_file_path: D:\temp\ubuntu.iso    # 4.5 GB
    big_block_size: 1024*1024*5  # 5MB
    block_size: 1024*4     # 4KB
    percentage: 100      # 100 %