log:
    log_file_path: log/memory.log

# readFile: D:\tools\fm20240923\fm20240923.zip
reader:
    # read_file_paths: [D:\temp\ubuntu.iso, D:\Software\VM_VirtualMachine]
    read_file_paths: [D:\Software\VM_VirtualMachine\ubuntu-22.10-use-mem]
    big_block_size: 1024*1024  # 1MB
    block_size: 1024*4     # 4KB
    range:
        lower: 0.0   # 30%
        higher: 0.3
    random_pre: true  # 若为true，则每次读取时都会生成一个随机的pre，相当于每次都读取不同的随机块
    prefix: kvd    # 随机字符串，在计算块名hash时使用，用于标识不同的批次
    is_batch_reading : false  # 是否分批次读取
    batch_size: 0.1  # 每次读取 10%

    small_file_size: 4*1024  # 小于4KB的文件，直接忽略

# 求解器使用的配置
solver_options: 
    p : 0.3